# Generated by Django 3.2 on 2021-05-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_Category',
            new_name='TaskCategory',
        ),
    ]
